import 'package:chat_group/core/models/character_skill.dart';
import 'package:chat_group/core/models/media_attachment.dart';

class AgentPromptBuilder {
  static String buildToolPlanningPrompt({
    required String characterName,
    required List<CharacterSkill> skills,
    required String userRequest,
    List<MediaAttachment>? media,
  }) {
    final skillText = skills.map((s) {
      final steps = s.instructions.map((i) => '- $i').join('\n');
      return 'Skill: ${s.name}\n'
          'Domain: ${s.domain}\n'
          'Description: ${s.description}\n'
          'Steps:\n$steps';
    }).join('\n\n');

    return '''
你是$characterName。你不是只能聊天的人设，你有可复用技能，并且要像真实专家一样工作。

用户请求：
$userRequest${mediaHint(media)}

你的技能：
$skillText

当你需要工具时，只输出一个工具请求块：
```agent_tool
{"tool":"workspace.read","reason":"为什么需要这个工具","args":{"path":"lib/main.dart"}}
```

可用工具名：
- workspace.list
- workspace.read
- workspace.patch
- command.run
- browser.context
- skill.create
- skill.download

创建新文件时，把**文件的完整内容**直接放进 `args.content`（不要写 diff / patch 格式，桥梁服务会原样写入）：
```agent_tool
{"tool":"workspace.patch","reason":"生成个人主页","args":{"path":"page.html","content":"<!doctype html>\\n<html lang=\\"zh-CN\\">\\n<head><meta charset=\\"utf-8\\"><title>页面</title></head>\\n<body><h1>你好</h1></body>\\n</html>"}}
```
注意：`content` 必须是该文件的**全部内容**（用户要什么就生成什么，不要写占位/空壳/模板），且不要添加任何作者签名、水印或 “generated by” 字样。

规则：
- 读文件、浏览器上下文、运行命令、写补丁之前说明原因。
- 当用户想生成文件、写 Markdown、导出图片/网页，却没有给出具体文件名时，你必须**主动指定一个合理的文件名**放在工具请求的 `path` 里（例如画面/场景类用 `star_scene.html`，报告类用 `report.md`，代码类用 `main.dart`）。不要只说"我没有收到权限申请"或让用户自己去生成文件——应先输出带 `path` 的工具请求，等待用户批准后由本地桥接服务写入工作目录。
- 当现有技能不够贴合角色职业时，用 skill.download 安装职业专家 skill；没有合适模板时再用 skill.create 创建。
- 如果用户要求生成文件、写 Markdown、改代码、读取路径或运行测试，不能只回复"正在做"或承诺稍后完成；必须输出工具请求，或明确说明缺少的权限、路径、bridge 服务或确认信息。
- 写入文件前必须等待用户批准。
- 如果信息不足且执行会有风险，先问一个具体问题。
- 如果用户是在追问或补充之前的请求，务必结合对话历史理解其真实意图，不要假装不知道之前发生过什么。
- 完成后用自然角色口吻总结做了什么、证据是什么、还有什么风险。
- **生成文件时严禁添加任何作者签名、水印、"generated by"、"生成角色"或其他标识 AI 身份的信息**——保持内容纯净，就像用户自己创建的一样。
''';
  }

  static String buildToolResultPrompt({
    required String characterName,
    required String userRequest,
    required String toolName,
    required Map<String, dynamic> toolResult,
  }) {
    final isFileWrite = toolName.contains('workspace.patch') ||
        toolName.contains('workspace.write');
    final writeOk = isFileWrite && toolResult['ok'] == true;

    return '''
你是$characterName。用户请求是：
$userRequest

工具 $toolName 返回：
$toolResult

${writeOk ? '''
⚠️ 文件已成功写入！任务已完成。
- 如果用户的任务只要求生成文件，直接给出最终答复（1-2 句话），说明文件已生成、做了什么即可
- **绝对不要**再次调用 workspace.patch 或任何写文件工具——文件已经写入成功了，重复写入只会生成多余的副本
- 只有用户还明确要求运行测试、检查结果等后续动作时，才可输出对应的非写入类 agent_tool 代码块
- **绝对不要**把文件内容、HTML、代码粘贴到回复里——用户可以通过附件查看完整文件
''' : '''
重要约束（违反会导致糟糕的用户体验）：
- **严禁**将生成的文件内容、代码、HTML、Markdown 或任何产物原文粘贴到你的回复中——文件已通过工具写入并作为附件发送给用户，无需重复
- 如果文件已成功生成，只需用 1-2 句话确认完成即可（如"文件已生成完毕，请查看附件"）
- 如果工具执行失败，简要说明失败原因和建议，**不要**尝试在聊天消息中贴代码来替代
- 保持回复简洁（不超过 3 句话），不要长篇大论

如果还需要另一个工具（且不是写文件/补丁类工具）才能真正完成用户请求，只输出一个新的 agent_tool 代码块。
如果已经完成，请用你的角色口吻给出最终答复，说明证据、已完成动作和剩余风险。
'''}''';
  }

  static String mediaHint(List<MediaAttachment>? media) {
    if (media == null || media.isEmpty) return '';
    final parts = <String>[];
    final images = media.where((m) => m.type == 'image').length;
    final videos = media.where((m) => m.type == 'video').length;
    final files =
        media.where((m) => m.type != 'image' && m.type != 'video').toList();
    if (images > 0) parts.add('[$images 张图片]');
    if (videos > 0) parts.add('[$videos 段视频]');
    if (files.isNotEmpty) {
      final names = files.take(3).map((f) => f.fileName ?? '文件').join('、');
      parts.add('[${files.length} 个文件：$names]');
    }
    if (parts.isEmpty) return '';
    return '\n（用户发送了附件：${parts.join('，')}）';
  }
}
