import 'package:chat_group/core/models/character_skill.dart';
import 'package:chat_group/core/models/media_attachment.dart';

class AgentPromptBuilder {
  /// Builds the Stage 03 prompt for the single strict JSON decision protocol.
  ///
  /// This method is intentionally separate from the legacy tool prompt. Task
  /// 13 defines the parser and prompt contract, and Task 18 routes production
  /// work mode through this strict decision contract.
  static String buildAgentDecisionPrompt({
    required String rolePlaySystemPrompt,
    required List<CharacterSkill> skills,
    required String userRequest,
    List<MediaAttachment>? media,
    String workModeContext = '',
  }) {
    final skillText = _formatSkills(skills);
    final identity = workModeContext.contains(rolePlaySystemPrompt)
        ? ''
        : '$rolePlaySystemPrompt\n\n';

    return '''
$identity你正在执行工作模式任务。每次只返回一个严格的 AgentDecision JSON object，不要输出解释、XML、Markdown code fence 或其他文本。

用户请求：
$userRequest${mediaHint(media)}

$workModeContext

可用技能：
$skillText

固定顶层字段（必须全部出现且不得增加字段）：action、public_update、tool、completion。
action 只能是 plan、tool、clarify、handoff、finish。
public_update 只写用户可见的动作、依据或结论，不写思维链、隐藏推理、内部分析或私有信息。

各 action 的 completion 结构：
- plan：tool 必须为 null；completion 为 {"steps":["步骤 1","步骤 2"]}。
- tool：completion 必须为 null；tool 为 {"name":"已注册工具名","arguments":{}}。arguments 必须是经过工具 schema 允许的 JSON object。
- command.run 的 arguments 必须包含 executable、arguments、workingDirectory、declaredImpact；workingDirectory 为空时由执行器自动解析为当前授权工作区根目录（见上方工作模式上下文），不要填写 `.`；declaredImpact 至少填写一个工作区内路径，例如 `.`。
- clarify：tool 必须为 null；completion 为 {"question":"需要用户回答的问题","options":["可选答案"]}。
- handoff：tool 必须为 null；completion 为 {"target":"目标角色 ID","summary":"公开交接摘要"}。
- finish：tool 必须为 null；completion 为 {"summary":"最终结论","evidence":["可验证证据"]}。

输出必须是裸 JSON，例如：{"action":"tool","public_update":"正在读取目标文件。","tool":{"name":"workspace.read","arguments":{"path":"lib/main.dart"}},"completion":null}
''';
  }

  static String buildToolPlanningPrompt({
    required String rolePlaySystemPrompt,
    required List<CharacterSkill> skills,
    required String userRequest,
    List<MediaAttachment>? media,
    String workModeContext = '',
  }) {
    final skillText = _formatSkills(skills);
    // WorkModePolicy already carries it in this context; avoid a second copy.
    final identity = workModeContext.contains(rolePlaySystemPrompt)
        ? ''
        : '$rolePlaySystemPrompt\n\n';

    return '''
$identity你不是只能聊天的人设，你有可复用技能，并且要像真实专家一样工作。

用户请求：
$userRequest${mediaHint(media)}

$workModeContext

你的技能：
$skillText

WorkBuddy 工作方式（严格按顺序在内部执行，不要泄露思维过程）：
1. **意图判断**：区分闲聊和任务，复述真正的目标与可观察完成标准。
2. **拆解执行步骤**：只拆当前任务必需的步骤；信息不足且会改变结果时，先问一个关键问题。
3. **调用最少必要工具**：读取最小上下文，逐步调用工具，不虚构工具结果。
4. **产出可交付物**：以文件、代码、清单或带来源的结论完成任务，不只给建议或承诺。
5. **交付前自检**：检查完整性、正确性、依赖、验证证据和未完成风险。
6. **简洁交付**：先给结论，再列可交付物、验证证据、未完成项或风险。

当你需要工具时，只输出一个工具请求块：
```agent_tool
{"tool":"workspace.read","reason":"为什么需要这个工具","args":{"path":"lib/main.dart"}}
```

可用工具名：
- workspace.list
- workspace.read
- workspace.search
- workspace.document（读取并分析文本、代码、PDF、DOCX、XLSX；图片需当前模型支持视觉）
- workspace.patch
- workspace.rename
- workspace.delete
- command.run
- browser.context（仅旧版 AgentRuntime；Stage 03 WorkAgentLoop 不注册此工具）
- skill.create
- skill.download

创建新文件时，把**文件的完整内容**直接放进 `args.content`（不要写 diff / patch 格式，当前执行器会按 schema 原样写入）：
```agent_tool
{"tool":"workspace.patch","reason":"生成个人主页","args":{"path":"page.html","content":"<!doctype html>\\n<html lang=\\"zh-CN\\">\\n<head><meta charset=\\"utf-8\\"><title>页面</title></head>\\n<body><h1>你好</h1></body>\\n</html>"}}
```
注意：`content` 必须是该文件的**全部内容**（用户要什么就生成什么，不要写占位/空壳/模板），且不要添加任何作者签名、水印或 “generated by” 字样。

规则：
- 读文件、浏览器上下文、运行命令、写补丁之前说明原因。
- 当用户想生成文件、写 Markdown、导出图片/网页，却没有给出具体文件名时，你必须**主动指定一个合理的文件名**放在工具请求的 `path` 里（例如画面/场景类用 `star_scene.html`，报告类用 `report.md`，代码类用 `main.dart`）。不要只说"我没有收到权限申请"或让用户自己去生成文件——应先输出带 `path` 的工具请求，等待用户批准后由执行器写入工作目录。
- 当现有技能不够贴合角色职业时，用 skill.download 安装职业专家 skill；没有合适模板时再用 skill.create 创建。
- 如果没有任何已安装技能匹配当前用户意图，必须先调用 skill.create，参数中给出具体名称、领域、描述、步骤和最小权限；创建成功后再继续原任务，不能只口头建议用户配置技能。
- 如果用户要求生成文件、写 Markdown、改代码、读取路径或运行测试，不能只回复"正在做"或承诺稍后完成；必须输出工具请求，或明确说明缺少的权限、路径、执行器或确认信息。
- 写入文件前必须等待用户批准。
- 如果信息不足且执行会有风险，先问一个具体问题。
- workspace.document 只返回与查询相关的有界片段和来源位置；音频、视频明确不支持，不要尝试安装转码工具。
- 如果用户是在追问或补充之前的请求，务必结合对话历史理解其真实意图，不要假装不知道之前发生过什么。
- 完成后用自然角色口吻总结做了什么、证据是什么、还有什么风险。
- **生成文件时严禁添加任何作者签名、水印、"generated by"、"生成角色"或其他标识 AI 身份的信息**——保持内容纯净，就像用户自己创建的一样。
''';
  }

  static String _formatSkills(List<CharacterSkill> skills) => skills.map((s) {
        final steps = s.instructions.map((i) => '- $i').join('\n');
        return 'Skill: ${s.name}\n'
            'Domain: ${s.domain}\n'
            'Description: ${s.description}\n'
            'Steps:\n$steps';
      }).join('\n\n');

  static String buildToolResultPrompt({
    required String rolePlaySystemPrompt,
    required String userRequest,
    required String toolName,
    required Map<String, dynamic> toolResult,
  }) {
    final isFileWrite = toolName.contains('workspace.patch') ||
        toolName.contains('workspace.write');
    final writeOk = isFileWrite && toolResult['ok'] == true;

    return '''
$rolePlaySystemPrompt

用户请求是：
$userRequest

工具 $toolName 返回：
$toolResult

最终交付规范：
- **先给结论**，不要用客套话或“我将会”开头。
- 明确列出**可交付物**（文件路径、代码、清单或结论）。
- 引用工具返回的**验证证据**，绝不虚构已运行的检查。
- 完成一次简短**自检**：目标是否完成、结果是否可用、依赖是否齐全。
- 明确说明**未完成项或风险**；没有则写“无”。

⚠️ 附件真实性规则（违反会产生严重误导，务必遵守）：
- 只有 workspace.patch / workspace.write 工具真正执行成功（工具返回的 ok=true）时，才可在回复中说"已生成文件 / 请查看附件 / 已作为附件发送"。
- 如果你执行的只是 skill.create、skill.download、browser.context、command.run 等非文件写入工具，**严禁**声称"已通过工作流生成文件"或"已作为附件发送"——这类工具不会创建任何用户可见的文件。
- 如果用户的请求是生成文件，但你最终没有执行任何写文件操作（或写文件工具未返回 ok=true），必须如实说明情况，绝不能虚构交付物或假装已发送附件。

${writeOk ? '''
⚠️ 文件已成功写入！任务已完成。
- 如果用户的任务只要求生成文件，直接给出最终答复（1-2 句话），说明文件已生成、做了什么即可
- **绝对不要**再次调用 workspace.patch 或任何写文件工具——文件已经写入成功了，重复写入只会生成多余的副本
- 只有用户还明确要求运行测试、检查结果等后续动作时，才可输出对应的非写入类 agent_tool 代码块
- **绝对不要**把文件内容、HTML、代码粘贴到回复里——用户可以通过附件查看完整文件
''' : '''
重要约束（违反会导致糟糕的用户体验）：
- **严禁**将生成的文件内容、代码、HTML、Markdown 或任何产物原文粘贴到你的回复中。
${isFileWrite ? '- 本次写文件工具未返回成功状态（ok≠true）：如实说明写入失败的原因与建议，**不要**说"已生成文件 / 请查看附件"——因为并未成功创建任何附件。' : '- 当前工具 `$toolName` 不是文件写入工具，因此不可能产生任何附件：**严禁**声称"已作为附件发送""已通过工作流生成文件"等话术；只需如实总结该工具做了什么。'}
- 如果工具执行失败，简要说明失败原因和建议，**不要**尝试在聊天消息中贴代码来替代。
- 如果还需要另一个工具（且不是写文件/补丁类工具）才能真正完成用户请求，只输出一个新的 agent_tool 代码块。
- 如果已经完成，请用你的角色口吻给出最终答复，说明证据、已完成动作和剩余风险。
- 保持回复简洁（不超过 3 句话），不要长篇大论。
'''}''';
  }

  static String mediaHint(List<MediaAttachment>? media) {
    if (media == null || media.isEmpty) return '';
    final parts = <String>[];
    final images = media.where((m) => m.type == 'image').length;
    final videos = media.where((m) => m.type == 'video').length;
    final files =
        media.where((m) => m.type != 'image' && m.type != 'video').toList();
    if (images > 0) parts.add('[$images 张图片]');
    if (videos > 0) parts.add('[$videos 段视频]');
    if (files.isNotEmpty) {
      final names = files.take(3).map((f) => f.fileName ?? '文件').join('、');
      parts.add('[${files.length} 个文件：$names]');
    }
    if (parts.isEmpty) return '';
    return '\n（用户发送了附件：${parts.join('，')}）';
  }
}
