import 'package:chat_group/core/models/tool_permission.dart';
import 'package:chat_group/features/agentic/expert_skill_template.dart';

const List<ExpertSkillTemplate> documentExpertSkillTemplates = [
  ExpertSkillTemplate(
    id: 'document.markdown-artifact',
    name: 'Markdown Document Artifact Expert',
    domain: 'writing',
    description: '生成结构完整、可直接交付的 Markdown 文档，并以真实文件写入和读回验证作为完成依据。',
    keywords: [
      'markdown',
      'md 文档',
      'md文档',
      '技术文档',
      '项目文档',
      '需求文档',
      '文档',
      '报告',
      'readme',
    ],
    instructions: [
      '确认文档的受众、用途、结构、必备事实和可观察的完成标准。',
      '生成完整 Markdown，保持标题层级合理，不用空占位和未实现的承诺充数。',
      '调用 workspace.patch 写入 .md 文件，不得只在聊天正文中粘贴或口头声称完成。',
      '读回文件并检查内容非空、标题层级和交付路径，再作为附件发送。',
    ],
    requiredPermissions: [
      ToolPermission.workspaceRead,
      ToolPermission.workspacePatch,
    ],
  ),
  ExpertSkillTemplate(
    id: 'document.word',
    name: 'Word Document Expert',
    domain: 'document',
    description: '处理 Word/DOCX 文档的结构化阅读、改写、排版要求和交付边界。',
    keywords: [
      'docx',
      'doc 文档',
      'docx 文档',
      'word 文档',
      'word文档',
      'word document',
      'word doc',
    ],
    instructions: [
      '识别标题层级、段落、表格、目录、页码、批注或修订等 Word 结构要求。',
      '读取或修改现有 DOCX 时保留事实、层级和用户指定的格式约束。',
      '生成 Word 交付物前确认当前运行时是否配置二进制文档写入器；没有时如实降级为 Markdown。',
      '不得把 Markdown 文本伪装成 DOCX，也不得在未真实写入文件时声称已发送附件。',
    ],
    requiredPermissions: [
      ToolPermission.workspaceRead,
      ToolPermission.workspacePatch,
    ],
  ),
  ExpertSkillTemplate(
    id: 'document.pdf',
    name: 'PDF Document Expert',
    domain: 'document',
    description: '处理 PDF 的内容提取、页码定位、报告组织和可验证交付。',
    keywords: [
      'pdf',
      'pdf 文件',
      'pdf文档',
      'pdf document',
      '便携式文档',
    ],
    instructions: [
      '阅读 PDF 时按页码或章节定位证据，区分原文事实、总结和推断。',
      '生成报告时先组织标题、摘要、正文、引用和附录，再检查内容完整性。',
      '生成 PDF 前确认当前运行时是否配置 PDF 写入/渲染工具；本机已检测到 pandoc/tectonic 时必须实际调用 command.run，不得依据旧上下文声称工具缺失。',
      '中文 PDF 使用 tectonic 时显式配置 xeCJK 与可用中文字体，并在交付前重新读取或检查 PDF，确认中文没有丢失或被裁切。',
      '不得把文本文件改名为 PDF，也不得把未执行的渲染或校验写成已完成。',
    ],
    requiredPermissions: [
      ToolPermission.workspaceRead,
      ToolPermission.workspacePatch,
    ],
  ),
  ExpertSkillTemplate(
    id: 'document.presentations',
    name: 'Presentation Expert',
    domain: 'document',
    description: '设计和审阅演示文稿/PPTX 的叙事结构、页面层级与交付内容。',
    keywords: [
      'ppt',
      'pptx',
      'ppt 文件',
      'pptx 文件',
      'powerpoint',
      '幻灯片',
      '演示文稿',
      '课件',
      'slides',
      'slide deck',
      'presentation',
    ],
    instructions: [
      '先明确受众、演讲目标和核心结论，再安排每页一个清晰的信息任务。',
      '为每页设计标题、关键证据、视觉层级和必要的演讲备注，避免把长文硬塞进页面。',
      '生成 PPTX 前确认当前运行时是否配置演示文稿写入器；没有时如实交付可审阅的 Markdown 大纲。',
      '交付前检查页序、重复内容、事实来源和文件格式，不把大纲伪装成已生成的 PPTX。',
    ],
    requiredPermissions: [
      ToolPermission.workspaceRead,
      ToolPermission.workspacePatch,
    ],
  ),
  ExpertSkillTemplate(
    id: 'document.spreadsheets',
    name: 'Spreadsheet Expert',
    domain: 'document',
    description: '处理 Excel/XLSX/XLS、CSV/TSV 表格的数据结构、公式、分析和校验。',
    keywords: [
      'excel',
      'xlsx',
      'xls',
      'excel 文件',
      '电子表格',
      '表格数据',
      'spreadsheet',
      'workbook',
      'csv',
      'tsv',
    ],
    instructions: [
      '先确认表头、字段类型、单位、主键、公式依赖和用户期望的分析结果。',
      '修改表格时保留数据含义，检查空值、重复、公式范围、合计和异常值。',
      '生成 XLSX 前确认当前运行时是否配置表格写入器；没有时如实交付 CSV 或 Markdown 表格。',
      '不得把 CSV/Markdown 改名成 XLSX，也不得在没有校验证据时声称公式或图表正确。',
    ],
    requiredPermissions: [
      ToolPermission.workspaceRead,
      ToolPermission.workspacePatch,
    ],
  ),
];
